source "https://rubygems.org"

# Para usar GitHub Pages
gem "github-pages", group: :jekyll_plugins

# Si quieres usar plugins específicos, añádelos aquí
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows y JRuby no incluyen archivos zoneinfo, así que incluye la gema tzinfo-data
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Mejora de rendimiento para observar directorios en Windows
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Bloquea la gema http_parser.rb en v0.6.x en construcciones JRuby
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

gem "webrick", "~> 1.8"

